theme: minima
title: The Guard Shack
author: admase
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Secure your network and information, fast

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
